Repository Villanueva-del-Trabuco-EGC/decide-part-1, pull requests merged in 2022-12, with the labels that each got.

#19 [FIX] Dockerfile arreglado
  docker/Dockerfile
Labels: desarrollo

#18 Selección atributos para csv del censo
  decide/census/census_utils.py
  decide/census/forms.py
  decide/census/templates/export_census.html
  decide/census/views.py
Labels: desarrollo

#21 [FIX] Eliminado paso innecesario en Actions
  .github/workflows/django.yml
Labels: bug

#22 Test traducción de booth al español
  decide/booth/tests.py
Labels: testeo

#23 Primero cambios para la traduccion en ingles.
  decide/authentication/locale/en_US/LC_MESSAGES/django.po
  decide/authentication/templates/authentication/register.html
  decide/authentication/templates/template_activate_account.html
  decide/base/templates/base.html
  decide/booth/locale/en_US/LC_MESSAGES/django.po
  decide/decide/settings.py
  decide/visualizer/templates/visualizer/visualizer.html
Labels: desarrollo

#17 Limitación /census/export
  decide/booth/templates/booth/votings.html
  decide/booth/urls.py
  decide/booth/views.py
  decide/census/views.py
  decide/decide/settings.py
Labels: bug, desarrollo

#25 [FIX] Arreglo template_account.html
  decide/authentication/locale/en_US/LC_MESSAGES/django.po
  decide/authentication/templates/template_activate_account.html
Labels: bug, desarrollo

#26 Tests de la rama "Graficas/davzamfer"
  decide/visualizer/static/graph.js
  decide/visualizer/templates/visualizer/visualizer.html
  decide/visualizer/tests.py
Labels: test

#27 [DES] Interfaz traducible actualizada.
  decide/authentication/locale/en_US/LC_MESSAGES/django.po
  decide/authentication/templates/authentication/register.html
  decide/base/templates/base.html
  decide/booth/templates/booth/booth.html
  decide/booth/templates/booth/votings.html
  decide/census/templates/census/census.html
  decide/visualizer/templates/visualizer/visualizer.html
Labels: desarrollo

#29 [DES] Actualizada grafias
  decide/visualizer/locale/es_ES/LC_MESSAGES/django.po
Labels: desarrollo

#30 Test unitario y manejo de errores
  decide/census/census_utils.py
  decide/census/templates/errors.html
  decide/census/tests.py
  decide/census/views.py
Labels: desarrollo, test

#36 [fix] Etiqueta formulario exportacion censo.
  decide/census/forms.py
  decide/census/templates/export_census.html
  decide/census/tests.py
Labels: fix

#35 [Desarrollo] Traduccion en ingles terminada.
  decide/authentication/locale/en_US/LC_MESSAGES/django.po
  decide/base/locale/en_US/LC_MESSAGES/django.po
  decide/booth/locale/en_US/LC_MESSAGES/django.po
  decide/census/locale/en_US/LC_MESSAGES/django.po
  decide/census/templates/export_census.html
  decide/decide/locale/en_US/LC_MESSAGES/django.po
  decide/decide/settings.py
  decide/gateway/locale/en_US/LC_MESSAGES/django.po
  decide/mixnet/locale/en_US/LC_MESSAGES/django.po
  decide/postproc/locale/en_US/LC_MESSAGES/django.po
  decide/store/locale/en_US/LC_MESSAGES/django.po
  decide/visualizer/locale/en_US/LC_MESSAGES/django.po
  decide/visualizer/templates/visualizer/visualizer.html
  decide/voting/locale/en_US/LC_MESSAGES/django.po
Labels: desarrollo

#40 [FIX] Traducciones arregladas
  decide/authentication/locale/es_ES/LC_MESSAGES/django.po
  decide/census/locale/es_ES/LC_MESSAGES/django.po
Labels: fix

#41 [test] Test acceso página export.
  decide/census/templates/errors.html
  decide/census/tests.py
  decide/census/views.py
Labels: test

#43 [DESARROLLO] Actualizada traducción de census
  decide/census/locale/es_ES/LC_MESSAGES/django.po
Labels: desarrollo

#42 [Desarrollo] Actualizacion de interfaz traducible census.
  decide/census/locale/en_US/LC_MESSAGES/django.po
  decide/census/templates/errors.html
Labels: desarrollo

#45 [Desarrollo] Tests de traduccion export census
  decide/census/tests.py
Labels: desarrollo

#46 [Test] Interfaz Traducible en español.
  decide/visualizer/tests.py
Labels: test

#48 [Desarrollo] Actualizacion interfaz traducible.
  decide/visualizer/locale/es_ES/LC_MESSAGES/django.po
  decide/visualizer/templates/visualizer/visualizer.html
Labels: desarrollo

#47 [Desarrollo] Añadidas traducciones
  decide/visualizer/locale/es_ES/LC_MESSAGES/django.po
Labels: desarrollo

#49 [test] Tests acceso página export.
  decide/census/tests.py
  decide/census/views.py
Labels: test

#51 [test] Test export census
  decide/census/tests.py
Labels: test

#52 [Test] Tests de traducción español visualizer
  decide/visualizer/tests.py
Labels: test

#53 [Desarrollo] [Fix] Arreglada funcionalidad de autenticación con github en Docker
  decide/decide/settings.py
  docker/docker-nginx.conf
Labels: desarrollo, fix

#57 [Desarrollo] Añadido login con Twitter y botón de logout
  .gitignore
  decide/booth/templates/booth/booth.html
  decide/booth/urls.py
  decide/booth/views.py
  decide/decide/settings.py
  requirements.txt
Labels: desarrollo

#60 [FIX] Fallo en traducción de booth
  decide/booth/locale/es_ES/LC_MESSAGES/django.po
Labels: fix

#55 Tests trad/pabmargom3 framigdom
  decide/decide/settings.py
  decide/decide/urls.py
  decide/visualizer/forms.py
  decide/visualizer/templates/visualizer/visualizer.html
  decide/visualizer/tests.py
  decide/visualizer/urls.py
  decide/visualizer/views.py
Labels: desarrollo, test, fix

#58 [Fix] Arreglada aparición de botones inesperada
  decide/booth/templates/booth/booth.html
Labels: fix

#59 [Fix][Test] Gráficas ocultas votacion no acabada
  decide/visualizer/templates/visualizer/visualizer.html
  decide/visualizer/tests.py
Labels: test, fix

#63 [FIX] Badges incorrectos
  README.md
Labels: fix

#65 [Fix] Arreglado supuesto error de traduccion.
  decide/visualizer/tests.py
Labels: fix

#67 Traducción inglés de booth.html
  decide/booth/locale/en_US/LC_MESSAGES/django.po
  decide/booth/templates/booth/booth.html
Labels: desarrollo

#68 Arreglo de los tests en GitHub Actions
  decide/booth/tests.py
  decide/census/tests.py
Labels: fix

#64 [FIX] Error en actions de release
  .github/workflows/releases_workflow.yml
Labels: fix

#69 [FIx] Arreglada vista de votaciones
  decide/booth/templates/booth/votings.html
Labels: fix

#70 [Test] Añadido tests para booth y refractorizados
  decide/booth/tests.py
  decide/census/tests.py
Labels: test
